
model_list:
  - model_name: reasoning
    litellm_params:
      model: openai/clowman/Llama-3.1-405B-Instruct-AWQ-Int4
      api_base: http://vllm-reasoning:8000/v1
      api_key: "EMPTY"

  - model_name: multimodal
    litellm_params:
      model: openai/Qwen/Qwen3-Omni-30B-A3B-Instruct
      api_base: http://vllm-multimodal:8000/v1
      api_key: "EMPTY"

litellm_settings:
  drop_params: True
